services:
  generator:
    build:
      context: ..
      dockerfile: docker/generator.Dockerfile
    volumes:
      - ../logs:/app/logs
      - ../charts:/app/charts  # Charts output
      - ../generator:/app  # Mount the generator source code
    stdin_open: true
    tty: true

  train_model:
    build:
      context: ..
      dockerfile: docker/train_model.Dockerfile
    volumes:
      - ../logs:/app/logs  # Shared logs folder
      - ../models:/app/models  # Model output
      - ../charts:/app/charts  # Charts output
      - ../analyzer:/app  # Mount the analyzer source code
    stdin_open: true
    tty: true

  test_model:
    build:
      context: ..
      dockerfile: docker/test_model.Dockerfile
    volumes:
      - ../logs:/app/logs  # Shared logs folder
      - ../models:/app/models  # Load trained model and scaler
      - ../charts:/app/charts  # Charts output
      - ../analyzer:/app  # Mount the analyzer source code
    stdin_open: true
    tty: true
